### ISSUE TITLE
Login API not working

### ISSUE THREAD

**Issue by kumarsukhani** [5paisa/go5paisa#1]
Getting this error:

`{"body":null,"head":{"responseCode":"5PLoginV2","status":"2","statusDescription":"Invalid head parameters."}}
`

Please let me know how to fix this.

**Comment by invinciblycool** [comment]
Hey @kumarsukhani Thanks for your interest in using the Golang SDK for 5paisa trading APIs

Are you facing this with the **Golang** SDK?

**Comment by kumarsukhani** [comment]
Yes.

**Comment by invinciblycool** [comment]
Can you please share your code snippet without the credentials(or masked credentials)

**Comment by kumarsukhani** [comment]
Hi,

I am referring the code snippet in the Readme. I have just changed the
credentials.

**Comment by invinciblycool** [comment]
Can you please refer to the README again.
I had made a few changes and you might not have updated those. Or you could just plug in your credentials in the below code.
Also, please double check and copy values from https://www.5paisa.com/developerapi/apikeys

```go
package main

import (
	"fmt"
	"github.com/5paisa/go5paisa"
)

func main() {

	conf := &go5paisa.Config{
		AppName:       "",
		AppSource:     "",
		UserID:        "",
		Password:      "",
		UserKey:       "",
		EncryptionKey: "",
	}
	appConfig := go5paisa.Init(conf)
	client, err := go5paisa.Login(appConfig, "xyz@gmail.com", "password", "YYYYMMDD")
	if err != nil {
		panic(err)
	}
	holdings, err := client.GetHoldings()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", holdings)
}

```

**Comment by kumarsukhani** [comment]
Hi, 

I tried what you said above, even cross-checked the credentials, but still the same error.

**Comment by kumarsukhani** [comment]
Same code which was giving error yesterday, now working fine. Very strange. 
Anyways thanks for your help.

**Comment by invinciblycool** [comment]
No problem @kumarsukhani 
Feel free to open issues if you face any problems :tada: 
Also, I'll be adding more examples here at https://github.com/5paisa/go5paisa/tree/master/examples
