### ISSUE TITLE
GetPositions not working because of incorrect datatypes of Positions struct

### ISSUE THREAD

**Issue by niranjan92** [5paisa/go5paisa#3]
Need to update data types of fields to get it working 

https://github.com/5paisa/go5paisa/compare/master...niranjan92:master

ignore the go.mod

**Comment by invinciblycool** [comment]
Oops. Must've missed that.
Thanks for pointing that out.
https://github.com/5paisa/go5paisa/commit/5c12bafe62bc786b8335a730880a575f55ee02b6 Fixes it!

Thanks again :tada:
